check50:
  files: &check50_files
    - !exclude "*"
    - !include "helloworld.py"
    
  checks:
      Hello World:
        - run: python3 helloworld.py
          stdout: Hello world!

submit50:
  files: *check50_files
