check50:
  files: &check50_files
    - !exclude "*"
    - !include "helloname.py"
    
  checks:
      Hello Kyle:
        - run: python3 helloname.py 
          stdin: 
            - Kyle
          stdout: Hello, Kyle

submit50:
  files: *check50_files
